import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { AuthUser } from "../models/access-control.model";
import { CreateProposicaoDto } from "../models/proposicoes/proposicao.model";
import { AuthResponse } from "../models/responses.model";
import UsersApi from "../services/api/users.api";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    const [token, setToken] = useState("");
    const usersAPI = new UsersApi();

    const loginHandler = async () => {
        const authUser = new AuthUser();
        authUser.username = "urielf";
        authUser.password = "W$BcEbrgq33!";

        const authResponse: AuthResponse = await usersAPI.login(authUser);
        console.log(authResponse);
        setToken(authResponse.token);
    };

    const postProposicaoHandler = () => {
        const proposicao = new CreateProposicaoDto();
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>CPTM - GRD</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>CPTM - GRD</h1>

                <p className={styles.description}>Teste de API</p>
                <p className={styles.description}>Token: {token}</p>

                <div className={styles.grid}>
                    <a className={styles.card} onClick={loginHandler}>
                        <h2>Login &rarr;</h2>
                        <p>Faz login.</p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
