// <auto-generated />
using System;
using CPTM.GRD.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CPTM.GRD.Persistence.Migrations
{
    [DbContext(typeof(GrdContext))]
    [Migration("20220727183521_ExistingViewsAndConfiguration")]
    partial class ExistingViewsAndConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GRD")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CPTM.GRD.Persistence.ConfigurationTables.GrdConfiguracao", b =>
                {
                    b.Property<string>("Parametro")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("PARAMETRO");

                    b.Property<DateTime?>("DtAlteracao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_ALTERACAO");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<int?>("IdCodusuarioAlteracao")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_CODUSUARIO_ALTERACAO");

                    b.Property<int>("IdCodusuarioCadastro")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_CODUSUARIO_CADASTRO");

                    b.Property<string>("TxDescricao")
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("TX_DESCRICAO");

                    b.Property<string>("Valor")
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("VALOR");

                    b.HasKey("Parametro")
                        .HasName("PK_CONFIGURACAO");

                    b.ToTable("GRD_CONFIGURACAO", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.ConfigurationTables.GrdUsuarioPreferencia", b =>
                {
                    b.Property<int>("IdCodUsuario")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("ID_CODUSUARIO");

                    b.Property<string>("TxCategoria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_CATEGORIA");

                    b.Property<string>("TxValor")
                        .HasColumnType("CLOB")
                        .HasColumnName("TX_VALOR");

                    b.HasKey("IdCodUsuario", "TxCategoria")
                        .HasName("PK_USUARIO_PREFERENCIA");

                    b.ToTable("GRD_USUARIO_PREFERENCIA", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwCargo", b =>
                {
                    b.Property<bool?>("FlAtivo")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_ATIVO");

                    b.Property<int>("IdCargo")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CARGO");

                    b.Property<string>("TxCargo")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("TX_CARGO");

                    b.ToView("GRD_VW_CARGO");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwCasisGrupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_GRUPO");

                    b.Property<int>("IdSistema")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_SISTEMA");

                    b.Property<string>("TxDescrGrupo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_DESCR_GRUPO");

                    b.Property<string>("TxSigla")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("TX_SIGLA");

                    b.ToView("GRD_VW_CASIS_GRUPO");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwCasisGrupoUsuario", b =>
                {
                    b.Property<int>("IdCodusuario")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("ID_CODUSUARIO");

                    b.Property<int>("IdGrupo")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_GRUPO");

                    b.ToView("GRD_VW_CASIS_GRUPO_USUARIO");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwEstruturaOrg", b =>
                {
                    b.Property<string>("CdCentroCusto")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("CD_CENTRO_CUSTO");

                    b.Property<string>("CdTipoEstrutura")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("CD_TIPO_ESTRUTURA");

                    b.Property<string>("DepSigla")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("DEP_SIGLA");

                    b.Property<string>("DirSigla")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("DIR_SIGLA");

                    b.Property<decimal?>("FlAtivo")
                        .HasColumnType("NUMBER")
                        .HasColumnName("FL_ATIVO");

                    b.Property<string>("GerSigla")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("GER_SIGLA");

                    b.Property<string>("GgSigla")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("GG_SIGLA");

                    b.Property<string>("IdEstrutura")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(40)")
                        .HasColumnName("ID_ESTRUTURA");

                    b.Property<decimal?>("NrNivel")
                        .HasColumnType("NUMBER")
                        .HasColumnName("NR_NIVEL");

                    b.Property<string>("TxBairro")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_BAIRRO");

                    b.Property<string>("TxCidade")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_CIDADE");

                    b.Property<string>("TxComplemento")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(25)")
                        .HasColumnName("TX_COMPLEMENTO");

                    b.Property<string>("TxEnderecoCompleto")
                        .HasMaxLength(211)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(211)")
                        .HasColumnName("TX_ENDERECO_COMPLETO");

                    b.Property<string>("TxEstado")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(2)")
                        .HasColumnName("TX_ESTADO");

                    b.Property<string>("TxLogradouro")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(60)")
                        .HasColumnName("TX_LOGRADOURO");

                    b.Property<string>("TxNome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_NOME");

                    b.Property<string>("TxNomeReduzido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_NOME_REDUZIDO");

                    b.Property<string>("TxNumero")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("TX_NUMERO");

                    b.Property<string>("TxSigla")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("TX_SIGLA");

                    b.Property<string>("TxTipoEstrutura")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TX_TIPO_ESTRUTURA");

                    b.ToView("GRD_VW_ESTRUTURA_ORG");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwFuncao", b =>
                {
                    b.Property<bool?>("FlAtivo")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_ATIVO");

                    b.Property<int>("IdFuncao")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_FUNCAO");

                    b.Property<string>("TxFuncao")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_FUNCAO");

                    b.ToView("GRD_VW_FUNCAO");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwUsuario", b =>
                {
                    b.Property<decimal?>("CdFuncionario")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CD_FUNCIONARIO");

                    b.Property<string>("CdSexo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("CD_SEXO")
                        .IsFixedLength();

                    b.Property<string>("CdStatusEmpregado")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(2)")
                        .HasColumnName("CD_STATUS_EMPREGADO");

                    b.Property<string>("CdTipoFuncionario")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(2)")
                        .HasColumnName("CD_TIPO_FUNCIONARIO");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("CPF");

                    b.Property<DateTime?>("DtAdmissao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_ADMISSAO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime?>("DtDemissao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_DEMISSAO");

                    b.Property<DateTime?>("DtDesligamentoTerceiro")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_DESLIGAMENTO_TERCEIRO");

                    b.Property<DateTime?>("DtExpiracao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_EXPIRACAO");

                    b.Property<DateTime?>("DtNascimento")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<bool?>("FlAtivo")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_ATIVO");

                    b.Property<bool?>("FlAtivoAd")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_ATIVO_AD");

                    b.Property<bool?>("FlAtvNrm")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_ATV_NRM");

                    b.Property<bool?>("FlEmpregado")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_EMPREGADO");

                    b.Property<int?>("IdCargo")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CARGO");

                    b.Property<int?>("IdChefePonto")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_CHEFE_PONTO");

                    b.Property<int>("IdCodusuario")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_CODUSUARIO");

                    b.Property<int?>("IdCodusuarioGestorAd")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_CODUSUARIO_GESTOR_AD");

                    b.Property<int?>("IdFuncao")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_FUNCAO");

                    b.Property<int?>("IdMix")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MIX");

                    b.Property<string>("Matricula")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("MATRICULA");

                    b.Property<string>("MatriculaAntiga")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("MATRICULA_ANTIGA");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("RG");

                    b.Property<string>("TxApelido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_APELIDO");

                    b.Property<string>("TxBilheteServico")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("TX_BILHETE_SERVICO");

                    b.Property<string>("TxCargo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_CARGO");

                    b.Property<string>("TxCep")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("TX_CEP");

                    b.Property<string>("TxCidade")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_CIDADE");

                    b.Property<string>("TxEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_EMAIL");

                    b.Property<string>("TxEmpresa")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(40)")
                        .HasColumnName("TX_EMPRESA");

                    b.Property<string>("TxEndereco")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_ENDERECO");

                    b.Property<string>("TxEstado")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(40)")
                        .HasColumnName("TX_ESTADO");

                    b.Property<string>("TxEstrutura")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(40)")
                        .HasColumnName("TX_ESTRUTURA");

                    b.Property<string>("TxFax")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("TX_FAX");

                    b.Property<string>("TxFuncao")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_FUNCAO");

                    b.Property<string>("TxMatricAlternativa")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TX_MATRIC_ALTERNATIVA");

                    b.Property<string>("TxNomeusuario")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_NOMEUSUARIO");

                    b.Property<string>("TxSiglaArea")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("TX_SIGLA_AREA");

                    b.Property<string>("TxSite")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_SITE");

                    b.Property<string>("TxStatusEmpregado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_STATUS_EMPREGADO");

                    b.Property<string>("TxTelefone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("TX_TELEFONE");

                    b.Property<string>("TxTelefoneCelular")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("TX_TELEFONE_CELULAR");

                    b.Property<string>("TxTipoChefe")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("TX_TIPO_CHEFE");

                    b.Property<string>("TxTipoFuncionario")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("TX_TIPO_FUNCIONARIO");

                    b.Property<string>("TxUsername")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TX_USERNAME");

                    b.ToView("GRD_VW_USUARIO");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwUsuarioFoto", b =>
                {
                    b.Property<bool>("FlTratada")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_TRATADA");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("BLOB")
                        .HasColumnName("FOTO");

                    b.Property<int>("IdCodusuario")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("ID_CODUSUARIO");

                    b.ToView("GRD_VW_USUARIO_FOTO");
                });
#pragma warning restore 612, 618
        }
    }
}
