// <auto-generated />
using System;
using CPTM.GRD.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CPTM.GRD.Persistence.Migrations
{
    [DbContext(typeof(GrdContext))]
    partial class GrdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GRD")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence("SEQ_ACOES")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SEQ_ANDAMENTOS")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SEQ_GROUPS")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SEQ_LOGS_ACAO")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SEQ_LOGS_PROPOSICAO")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SEQ_LOGS_REUNIAO")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SEQ_PARTICIPANTES")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SEQ_PROPOSICOES")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SEQ_RESOLUCOES")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SEQ_REUNIOES")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SEQ_USERS")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SEQ_VOTOS")
                .IncrementsBy(10);

            modelBuilder.Entity("CPTM.GRD.Domain.AccessControl.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_GROUPS");

                    b.Property<string>("Diretoria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Gerencia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("SiglaDiretoria")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("SiglaGerencia")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.HasKey("Id");

                    b.ToTable("GRD_GROUPS", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.AccessControl.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_USERS");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NivelAcesso")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UsernameAd")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.HasKey("Id");

                    b.ToTable("GRD_USERS", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Acoes.Acao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_ACOES");

                    b.Property<int>("AlertaVencimento")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Arquivada")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Definicao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("DiasParaVencimento")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DiretoriaResId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EmailDiretor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NumeroContrato")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Periodicidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("PrazoFinal")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("PrazoInicial")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("PrazoProrrogadoDias")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DiretoriaResId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("GRD_ACOES", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Acoes.Children.Andamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_ANDAMENTOS");

                    b.Property<int?>("AcaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("AnexosFilePaths")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.HasIndex("UserId");

                    b.ToTable("GRD_ANDAMENTOS", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Logging.LogAcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_LOGS_ACAO");

                    b.Property<int?>("AcaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("AcaoRef")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Diferenca")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("RespId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.HasIndex("RespId");

                    b.ToTable("GRD_LOGS_ACAO", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Logging.LogProposicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_LOGS_PROPOSICAO");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Diferenca")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("PropId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ProposicaoRef")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("RespId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PropId");

                    b.HasIndex("RespId");

                    b.ToTable("GRD_LOGS_PROPOSICAO", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Logging.LogReuniao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_LOGS_REUNIAO");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Diferenca")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("RespId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ReuniaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ReuniaoRef")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("RespId");

                    b.HasIndex("ReuniaoId");

                    b.ToTable("GRD_LOGS_REUNIAO", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Proposicoes.Children.Resolucao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_RESOLUCOES");

                    b.Property<string>("AssinaturaResolucao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NumeroResolucao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ResolucaoDiretoria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ResolucaoFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("GRD_RESOLUCOES", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Proposicoes.Children.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_VOTOS");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ProposicaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("VotoRd")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId");

                    b.HasIndex("ProposicaoId");

                    b.ToTable("GRD_VOTOS", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Proposicoes.Proposicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_PROPOSICOES");

                    b.Property<string>("AjustesRd")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("AnotacoesPrevia")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("AreaAtual")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("AreaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Arquivada")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("CompetenciasConformeNormas")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("CriadorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CronogramaFisFinFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataBaseValor")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Deliberacao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DescProxPasso")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DescricaoFluxo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DescricaoProposicao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EditalFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("FimVigenciaReserva")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IdPrd")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("InicioVigenciaReserva")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsExtraPauta")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MotivoRetornoDiretoriaResp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MotivoRetornoGrg")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NotaTecnicaFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NumeroConselho")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NumeroProcessoLicit")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NumeroProposicao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NumeroReservaVerba")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Objeto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ObservacoesCustos")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OutrasObservacoes")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OutrosFilePath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ParecerJuridicoFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PcaFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PlanilhaQuantFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PossuiParecerJuridico")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("PrdFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ProtoloExpediente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RavFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ReceitaDespesa")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("RelatorioTecnicoFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ReservaVerbaFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ResolucaoDiretoriaFilePath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ResumoGeralResolucao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("ReuniaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ReuniaoId1")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ScFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Seq")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("SinteseProcessoFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TempoPermProx")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TempoPrevPerm")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Termo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TrFilePath")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<float>("ValorAtualContrato")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("ValorOriginalContrato")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("ValorReservaVerba")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("ValorTotalProposicao")
                        .HasColumnType("BINARY_FLOAT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CriadorId");

                    b.HasIndex("ReuniaoId");

                    b.HasIndex("ReuniaoId1");

                    b.ToTable("GRD_PROPOSICOES", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Reunioes.Children.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_PARTICIPANTES");

                    b.Property<int>("AreaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GRD_PARTICIPANTES", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Reunioes.Reuniao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_REUNIOES");

                    b.Property<string>("AtaFilePath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Comunicado")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataPrevia")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("HorarioPrevia")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MemoriaPreviaFilePath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MensagemEMail")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NumeroReuniao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("OutrasObservacoes")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PautaDefinitivaFilePath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PautaPreviaFilePath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RelatorioDeliberativoFilePath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TipoReuniao")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("GRD_REUNIOES", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.ConfigurationTables.GrdConfiguracao", b =>
                {
                    b.Property<string>("Parametro")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("PARAMETRO");

                    b.Property<DateTime?>("DtAlteracao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_ALTERACAO");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<int?>("IdCodusuarioAlteracao")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_CODUSUARIO_ALTERACAO");

                    b.Property<int>("IdCodusuarioCadastro")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_CODUSUARIO_CADASTRO");

                    b.Property<string>("TxDescricao")
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("TX_DESCRICAO");

                    b.Property<string>("Valor")
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("VALOR");

                    b.HasKey("Parametro")
                        .HasName("PK_CONFIGURACAO");

                    b.ToTable("GRD_CONFIGURACAO", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.ConfigurationTables.GrdUsuarioPreferencia", b =>
                {
                    b.Property<int>("IdCodUsuario")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("ID_CODUSUARIO");

                    b.Property<string>("TxCategoria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_CATEGORIA");

                    b.Property<string>("TxValor")
                        .HasColumnType("CLOB")
                        .HasColumnName("TX_VALOR");

                    b.HasKey("IdCodUsuario", "TxCategoria")
                        .HasName("PK_USUARIO_PREFERENCIA");

                    b.ToTable("GRD_USUARIO_PREFERENCIA", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwCargo", b =>
                {
                    b.Property<bool?>("FlAtivo")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_ATIVO");

                    b.Property<int>("IdCargo")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CARGO");

                    b.Property<string>("TxCargo")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("TX_CARGO");

                    b.ToView("GRD_VW_CARGO");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwCasisGrupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_GRUPO");

                    b.Property<int>("IdSistema")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_SISTEMA");

                    b.Property<string>("TxDescrGrupo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_DESCR_GRUPO");

                    b.Property<string>("TxSigla")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("TX_SIGLA");

                    b.ToView("GRD_VW_CASIS_GRUPO");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwCasisGrupoUsuario", b =>
                {
                    b.Property<int>("IdCodusuario")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("ID_CODUSUARIO");

                    b.Property<int>("IdGrupo")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_GRUPO");

                    b.ToView("GRD_VW_CASIS_GRUPO_USUARIO");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwEstruturaOrg", b =>
                {
                    b.Property<string>("CdCentroCusto")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("CD_CENTRO_CUSTO");

                    b.Property<string>("CdTipoEstrutura")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("CD_TIPO_ESTRUTURA");

                    b.Property<string>("DepSigla")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("DEP_SIGLA");

                    b.Property<string>("DirSigla")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("DIR_SIGLA");

                    b.Property<decimal?>("FlAtivo")
                        .HasColumnType("NUMBER")
                        .HasColumnName("FL_ATIVO");

                    b.Property<string>("GerSigla")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("GER_SIGLA");

                    b.Property<string>("GgSigla")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("GG_SIGLA");

                    b.Property<string>("IdEstrutura")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(40)")
                        .HasColumnName("ID_ESTRUTURA");

                    b.Property<decimal?>("NrNivel")
                        .HasColumnType("NUMBER")
                        .HasColumnName("NR_NIVEL");

                    b.Property<string>("TxBairro")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_BAIRRO");

                    b.Property<string>("TxCidade")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_CIDADE");

                    b.Property<string>("TxComplemento")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(25)")
                        .HasColumnName("TX_COMPLEMENTO");

                    b.Property<string>("TxEnderecoCompleto")
                        .HasMaxLength(211)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(211)")
                        .HasColumnName("TX_ENDERECO_COMPLETO");

                    b.Property<string>("TxEstado")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(2)")
                        .HasColumnName("TX_ESTADO");

                    b.Property<string>("TxLogradouro")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(60)")
                        .HasColumnName("TX_LOGRADOURO");

                    b.Property<string>("TxNome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_NOME");

                    b.Property<string>("TxNomeReduzido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_NOME_REDUZIDO");

                    b.Property<string>("TxNumero")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("TX_NUMERO");

                    b.Property<string>("TxSigla")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("TX_SIGLA");

                    b.Property<string>("TxTipoEstrutura")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TX_TIPO_ESTRUTURA");

                    b.ToView("GRD_VW_ESTRUTURA_ORG");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwFuncao", b =>
                {
                    b.Property<bool?>("FlAtivo")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_ATIVO");

                    b.Property<int>("IdFuncao")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_FUNCAO");

                    b.Property<string>("TxFuncao")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_FUNCAO");

                    b.ToView("GRD_VW_FUNCAO");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwUsuario", b =>
                {
                    b.Property<decimal?>("CdFuncionario")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CD_FUNCIONARIO");

                    b.Property<string>("CdSexo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("CD_SEXO")
                        .IsFixedLength();

                    b.Property<string>("CdStatusEmpregado")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(2)")
                        .HasColumnName("CD_STATUS_EMPREGADO");

                    b.Property<string>("CdTipoFuncionario")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(2)")
                        .HasColumnName("CD_TIPO_FUNCIONARIO");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("CPF");

                    b.Property<DateTime?>("DtAdmissao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_ADMISSAO");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime?>("DtDemissao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_DEMISSAO");

                    b.Property<DateTime?>("DtDesligamentoTerceiro")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_DESLIGAMENTO_TERCEIRO");

                    b.Property<DateTime?>("DtExpiracao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_EXPIRACAO");

                    b.Property<DateTime?>("DtNascimento")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<bool?>("FlAtivo")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_ATIVO");

                    b.Property<bool?>("FlAtivoAd")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_ATIVO_AD");

                    b.Property<bool?>("FlAtvNrm")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_ATV_NRM");

                    b.Property<bool?>("FlEmpregado")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_EMPREGADO");

                    b.Property<int?>("IdCargo")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CARGO");

                    b.Property<int?>("IdChefePonto")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_CHEFE_PONTO");

                    b.Property<int>("IdCodusuario")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_CODUSUARIO");

                    b.Property<int?>("IdCodusuarioGestorAd")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_CODUSUARIO_GESTOR_AD");

                    b.Property<int?>("IdFuncao")
                        .HasPrecision(6)
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("ID_FUNCAO");

                    b.Property<int?>("IdMix")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MIX");

                    b.Property<string>("Matricula")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("MATRICULA");

                    b.Property<string>("MatriculaAntiga")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("MATRICULA_ANTIGA");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("RG");

                    b.Property<string>("TxApelido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_APELIDO");

                    b.Property<string>("TxBilheteServico")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("TX_BILHETE_SERVICO");

                    b.Property<string>("TxCargo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_CARGO");

                    b.Property<string>("TxCep")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("TX_CEP");

                    b.Property<string>("TxCidade")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_CIDADE");

                    b.Property<string>("TxEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_EMAIL");

                    b.Property<string>("TxEmpresa")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(40)")
                        .HasColumnName("TX_EMPRESA");

                    b.Property<string>("TxEndereco")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_ENDERECO");

                    b.Property<string>("TxEstado")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(40)")
                        .HasColumnName("TX_ESTADO");

                    b.Property<string>("TxEstrutura")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(40)")
                        .HasColumnName("TX_ESTRUTURA");

                    b.Property<string>("TxFax")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("TX_FAX");

                    b.Property<string>("TxFuncao")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_FUNCAO");

                    b.Property<string>("TxMatricAlternativa")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TX_MATRIC_ALTERNATIVA");

                    b.Property<string>("TxNomeusuario")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TX_NOMEUSUARIO");

                    b.Property<string>("TxSiglaArea")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("TX_SIGLA_AREA");

                    b.Property<string>("TxSite")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_SITE");

                    b.Property<string>("TxStatusEmpregado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TX_STATUS_EMPREGADO");

                    b.Property<string>("TxTelefone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("TX_TELEFONE");

                    b.Property<string>("TxTelefoneCelular")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("TX_TELEFONE_CELULAR");

                    b.Property<string>("TxTipoChefe")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("TX_TIPO_CHEFE");

                    b.Property<string>("TxTipoFuncionario")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("TX_TIPO_FUNCIONARIO");

                    b.Property<string>("TxUsername")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TX_USERNAME");

                    b.ToView("GRD_VW_USUARIO");
                });

            modelBuilder.Entity("CPTM.GRD.Persistence.Views.GrdVwUsuarioFoto", b =>
                {
                    b.Property<bool>("FlTratada")
                        .HasPrecision(1)
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_TRATADA");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("BLOB")
                        .HasColumnName("FOTO");

                    b.Property<int>("IdCodusuario")
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("ID_CODUSUARIO");

                    b.ToView("GRD_VW_USUARIO_FOTO");
                });

            modelBuilder.Entity("GRD_ACAO_REUNIAO", b =>
                {
                    b.Property<int>("AcaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ReuniaoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("AcaoId", "ReuniaoId");

                    b.HasIndex("ReuniaoId");

                    b.ToTable("GRD_ACAO_REUNIAO", "GRD");
                });

            modelBuilder.Entity("GRD_PART_REUNIAO", b =>
                {
                    b.Property<int>("PartId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ReuniaoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("PartId", "ReuniaoId");

                    b.HasIndex("ReuniaoId");

                    b.ToTable("GRD_PART_REUNIAO", "GRD");
                });

            modelBuilder.Entity("GRD_PARTPREV_REUNIAO", b =>
                {
                    b.Property<int>("PartId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ReuId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("PartId", "ReuId");

                    b.HasIndex("ReuId");

                    b.ToTable("GRD_PARTPREV_REUNIAO", "GRD");
                });

            modelBuilder.Entity("GRD_USER_GROUP", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GRD_USER_GROUP", "GRD");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Acoes.Acao", b =>
                {
                    b.HasOne("CPTM.GRD.Domain.AccessControl.Group", "DiretoriaRes")
                        .WithMany()
                        .HasForeignKey("DiretoriaResId")
                        .IsRequired()
                        .HasConstraintName("FK_Acoes_Group");

                    b.HasOne("CPTM.GRD.Domain.AccessControl.User", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .IsRequired()
                        .HasConstraintName("FK_Acoes_User");

                    b.Navigation("DiretoriaRes");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Acoes.Children.Andamento", b =>
                {
                    b.HasOne("CPTM.GRD.Domain.Acoes.Acao", null)
                        .WithMany("Andamentos")
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Acoes_Andamento");

                    b.HasOne("CPTM.GRD.Domain.AccessControl.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Andamentos_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Logging.LogAcao", b =>
                {
                    b.HasOne("CPTM.GRD.Domain.Acoes.Acao", null)
                        .WithMany("Logs")
                        .HasForeignKey("AcaoId")
                        .HasConstraintName("FK_LogsA_Acao");

                    b.HasOne("CPTM.GRD.Domain.AccessControl.User", "Resp")
                        .WithMany()
                        .HasForeignKey("RespId")
                        .IsRequired()
                        .HasConstraintName("FK_LogsA_User");

                    b.Navigation("Resp");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Logging.LogProposicao", b =>
                {
                    b.HasOne("CPTM.GRD.Domain.Proposicoes.Proposicao", null)
                        .WithMany("Logs")
                        .HasForeignKey("PropId")
                        .HasConstraintName("FK_LogsP_Proposicao");

                    b.HasOne("CPTM.GRD.Domain.AccessControl.User", "Resp")
                        .WithMany()
                        .HasForeignKey("RespId")
                        .IsRequired()
                        .HasConstraintName("FK_LogsP_User");

                    b.Navigation("Resp");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Logging.LogReuniao", b =>
                {
                    b.HasOne("CPTM.GRD.Domain.AccessControl.User", "Resp")
                        .WithMany()
                        .HasForeignKey("RespId")
                        .IsRequired()
                        .HasConstraintName("FK_LogsR_User");

                    b.HasOne("CPTM.GRD.Domain.Reunioes.Reuniao", null)
                        .WithMany("Logs")
                        .HasForeignKey("ReuniaoId")
                        .HasConstraintName("FK_LogsR_Reuniao");

                    b.Navigation("Resp");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Proposicoes.Children.Voto", b =>
                {
                    b.HasOne("CPTM.GRD.Domain.Reunioes.Children.Participante", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId")
                        .IsRequired()
                        .HasConstraintName("FK_Votos_Part");

                    b.HasOne("CPTM.GRD.Domain.Proposicoes.Proposicao", null)
                        .WithMany("VotosRd")
                        .HasForeignKey("ProposicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Proposicoes_Voto");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Proposicoes.Proposicao", b =>
                {
                    b.HasOne("CPTM.GRD.Domain.AccessControl.Group", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .IsRequired()
                        .HasConstraintName("FK_Proposicoes_Group");

                    b.HasOne("CPTM.GRD.Domain.AccessControl.User", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId")
                        .IsRequired()
                        .HasConstraintName("FK_Proposicoes_User");

                    b.HasOne("CPTM.GRD.Domain.Reunioes.Reuniao", "Reuniao")
                        .WithMany("Proposicoes")
                        .HasForeignKey("ReuniaoId")
                        .HasConstraintName("FK_Reunioes_Prop");

                    b.HasOne("CPTM.GRD.Domain.Reunioes.Reuniao", null)
                        .WithMany("ProposicoesPrevia")
                        .HasForeignKey("ReuniaoId1")
                        .HasConstraintName("FK_Reunioes_PropPrev");

                    b.Navigation("Area");

                    b.Navigation("Criador");

                    b.Navigation("Reuniao");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Reunioes.Children.Participante", b =>
                {
                    b.HasOne("CPTM.GRD.Domain.AccessControl.Group", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .IsRequired()
                        .HasConstraintName("FK_Part_Group");

                    b.HasOne("CPTM.GRD.Domain.AccessControl.User", "User")
                        .WithOne()
                        .HasForeignKey("CPTM.GRD.Domain.Reunioes.Children.Participante", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Part_User");

                    b.Navigation("Area");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GRD_ACAO_REUNIAO", b =>
                {
                    b.HasOne("CPTM.GRD.Domain.Acoes.Acao", null)
                        .WithMany()
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_AcaoReuniao_AcaoId");

                    b.HasOne("CPTM.GRD.Domain.Reunioes.Reuniao", null)
                        .WithMany()
                        .HasForeignKey("ReuniaoId")
                        .IsRequired()
                        .HasConstraintName("FK_AcaoReuniao_ReuniaoId");
                });

            modelBuilder.Entity("GRD_PART_REUNIAO", b =>
                {
                    b.HasOne("CPTM.GRD.Domain.Reunioes.Children.Participante", null)
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_PartReuniao_PartId");

                    b.HasOne("CPTM.GRD.Domain.Reunioes.Reuniao", null)
                        .WithMany()
                        .HasForeignKey("ReuniaoId")
                        .IsRequired()
                        .HasConstraintName("FK_PartReuniao_ReuniaoId");
                });

            modelBuilder.Entity("GRD_PARTPREV_REUNIAO", b =>
                {
                    b.HasOne("CPTM.GRD.Domain.Reunioes.Children.Participante", null)
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_PartPrevReuniao_PartId");

                    b.HasOne("CPTM.GRD.Domain.Reunioes.Reuniao", null)
                        .WithMany()
                        .HasForeignKey("ReuId")
                        .IsRequired()
                        .HasConstraintName("FK_PartPrevReuniao_ReuId");
                });

            modelBuilder.Entity("GRD_USER_GROUP", b =>
                {
                    b.HasOne("CPTM.GRD.Domain.AccessControl.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_UserGroup_GroupId");

                    b.HasOne("CPTM.GRD.Domain.AccessControl.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserGroup_UserId");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Acoes.Acao", b =>
                {
                    b.Navigation("Andamentos");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Proposicoes.Proposicao", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("VotosRd");
                });

            modelBuilder.Entity("CPTM.GRD.Domain.Reunioes.Reuniao", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Proposicoes");

                    b.Navigation("ProposicoesPrevia");
                });
#pragma warning restore 612, 618
        }
    }
}
