CREATE SEQUENCE "GRD"."SEQ_ACOES" START WITH 1 INCREMENT BY 10 NOMINVALUE NOMAXVALUE NOCYCLE
/

CREATE SEQUENCE "GRD"."SEQ_ANDAMENTOS" START WITH 1 INCREMENT BY 10 NOMINVALUE NOMAXVALUE NOCYCLE
/

CREATE SEQUENCE "GRD"."SEQ_GROUPS" START WITH 1 INCREMENT BY 10 NOMINVALUE NOMAXVALUE NOCYCLE
/

CREATE SEQUENCE "GRD"."SEQ_LOGS_ACAO" START WITH 1 INCREMENT BY 10 NOMINVALUE NOMAXVALUE NOCYCLE
/

CREATE SEQUENCE "GRD"."SEQ_LOGS_PROPOSICAO" START WITH 1 INCREMENT BY 10 NOMINVALUE NOMAXVALUE NOCYCLE
/

CREATE SEQUENCE "GRD"."SEQ_LOGS_REUNIAO" START WITH 1 INCREMENT BY 10 NOMINVALUE NOMAXVALUE NOCYCLE
/

CREATE SEQUENCE "GRD"."SEQ_PARTICIPANTES" START WITH 1 INCREMENT BY 10 NOMINVALUE NOMAXVALUE NOCYCLE
/

CREATE SEQUENCE "GRD"."SEQ_PROPOSICOES" START WITH 1 INCREMENT BY 10 NOMINVALUE NOMAXVALUE NOCYCLE
/

CREATE SEQUENCE "GRD"."SEQ_RESOLUCOES" START WITH 1 INCREMENT BY 10 NOMINVALUE NOMAXVALUE NOCYCLE
/

CREATE SEQUENCE "GRD"."SEQ_REUNIOES" START WITH 1 INCREMENT BY 10 NOMINVALUE NOMAXVALUE NOCYCLE
/

CREATE SEQUENCE "GRD"."SEQ_USERS" START WITH 1 INCREMENT BY 10 NOMINVALUE NOMAXVALUE NOCYCLE
/

CREATE SEQUENCE "GRD"."SEQ_VOTOS" START WITH 1 INCREMENT BY 10 NOMINVALUE NOMAXVALUE NOCYCLE
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_GROUPS" (
    "Id" NUMBER(10) NOT NULL,
    "Sigla" NVARCHAR2(250) NOT NULL,
    "Nome" NVARCHAR2(2000) NOT NULL,
    "SiglaGerencia" NVARCHAR2(250) NOT NULL,
    "Gerencia" NVARCHAR2(2000) NOT NULL,
    "SiglaDiretoria" NVARCHAR2(250) NOT NULL,
    "Diretoria" NVARCHAR2(2000) NOT NULL,
    CONSTRAINT "PK_GRD_GROUPS" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_RESOLUCOES" (
    "Id" NUMBER(10) NOT NULL,
    "NumeroResolucao" NUMBER(10) NOT NULL,
    "AssinaturaResolucao" NVARCHAR2(2000) NOT NULL,
    "ResolucaoDiretoria" NVARCHAR2(2000) NOT NULL,
    "ResolucaoFilePath" NVARCHAR2(2000) NOT NULL,
    CONSTRAINT "PK_GRD_RESOLUCOES" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_REUNIOES" (
    "Id" NUMBER(10) NOT NULL,
    "NumeroReuniao" NUMBER(10) NOT NULL,
    "Data" TIMESTAMP(7) NOT NULL,
    "Horario" TIMESTAMP(7) NOT NULL,
    "Status" NUMBER(10) NOT NULL,
    "DataPrevia" TIMESTAMP(7) NOT NULL,
    "HorarioPrevia" TIMESTAMP(7) NOT NULL,
    "Local" NVARCHAR2(2000) NOT NULL,
    "TipoReuniao" NUMBER(10) NOT NULL,
    "Comunicado" NVARCHAR2(2000),
    "OutrasObservacoes" NVARCHAR2(2000),
    "MensagemEMail" NVARCHAR2(2000),
    "PautaPreviaFilePath" NVARCHAR2(2000),
    "MemoriaPreviaFilePath" NVARCHAR2(2000),
    "PautaDefinitivaFilePath" NVARCHAR2(2000),
    "RelatorioDeliberativoFilePath" NVARCHAR2(2000),
    "AtaFilePath" NVARCHAR2(2000),
    CONSTRAINT "PK_GRD_REUNIOES" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_USERS" (
    "Id" NUMBER(10) NOT NULL,
    "Nome" NVARCHAR2(2000) NOT NULL,
    "UsernameAd" NVARCHAR2(250) NOT NULL,
    "NivelAcesso" NUMBER(10) NOT NULL,
    "Funcao" NVARCHAR2(2000) NOT NULL,
    "Email" NVARCHAR2(2000) NOT NULL,
    CONSTRAINT "PK_GRD_USERS" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_ACOES" (
    "Id" NUMBER(10) NOT NULL,
    "Tipo" NUMBER(10) NOT NULL,
    "DiretoriaResId" NUMBER(10) NOT NULL,
    "Definicao" NVARCHAR2(2000) NOT NULL,
    "Periodicidade" NUMBER(10) NOT NULL,
    "PrazoInicial" TIMESTAMP(7) NOT NULL,
    "Status" NUMBER(10) NOT NULL,
    "Arquivada" NUMBER(1) NOT NULL,
    "ResponsavelId" NUMBER(10) NOT NULL,
    "EmailDiretor" NVARCHAR2(2000) NOT NULL,
    "NumeroContrato" NVARCHAR2(2000),
    "Fornecedor" NVARCHAR2(2000),
    "PrazoProrrogadoDias" NUMBER(10) NOT NULL,
    "PrazoFinal" TIMESTAMP(7) NOT NULL,
    "DiasParaVencimento" NUMBER(10) NOT NULL,
    "AlertaVencimento" NUMBER(10) NOT NULL,
    CONSTRAINT "PK_GRD_ACOES" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Acoes_Group" FOREIGN KEY ("DiretoriaResId") REFERENCES "GRD"."GRD_GROUPS" ("Id"),
    CONSTRAINT "FK_Acoes_User" FOREIGN KEY ("ResponsavelId") REFERENCES "GRD"."GRD_USERS" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_LOGS_REUNIAO" (
    "Id" NUMBER(10) NOT NULL,
    "Tipo" NUMBER(10) NOT NULL,
    "ReuniaoRef" NVARCHAR2(2000) NOT NULL,
    "Diferenca" NVARCHAR2(2000) NOT NULL,
    "Data" TIMESTAMP(7) NOT NULL,
    "RespId" NUMBER(10) NOT NULL,
    "ReuniaoId" NUMBER(10),
    CONSTRAINT "PK_GRD_LOGS_REUNIAO" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LogsR_Reuniao" FOREIGN KEY ("ReuniaoId") REFERENCES "GRD"."GRD_REUNIOES" ("Id"),
    CONSTRAINT "FK_LogsR_User" FOREIGN KEY ("RespId") REFERENCES "GRD"."GRD_USERS" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_PARTICIPANTES" (
    "Id" NUMBER(10) NOT NULL,
    "UserId" NUMBER(10) NOT NULL,
    "AreaId" NUMBER(10) NOT NULL,
    "Nome" NVARCHAR2(2000) NOT NULL,
    "Email" NVARCHAR2(2000) NOT NULL,
    CONSTRAINT "PK_GRD_PARTICIPANTES" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Part_Group" FOREIGN KEY ("AreaId") REFERENCES "GRD"."GRD_GROUPS" ("Id"),
    CONSTRAINT "FK_Part_User" FOREIGN KEY ("UserId") REFERENCES "GRD"."GRD_USERS" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_PROPOSICOES" (
    "Id" NUMBER(10) NOT NULL,
    "IdPrd" NUMBER(10) NOT NULL,
    "Status" NUMBER(10) NOT NULL,
    "Arquivada" NUMBER(1) NOT NULL,
    "CriadorId" NUMBER(10) NOT NULL,
    "AreaId" NUMBER(10) NOT NULL,
    "Titulo" NVARCHAR2(2000) NOT NULL,
    "Objeto" NUMBER(10) NOT NULL,
    "DescricaoProposicao" NVARCHAR2(2000) NOT NULL,
    "PossuiParecerJuridico" NUMBER(1) NOT NULL,
    "ResumoGeralResolucao" NVARCHAR2(2000) NOT NULL,
    "ObservacoesCustos" NVARCHAR2(2000) NOT NULL,
    "CompetenciasConformeNormas" NVARCHAR2(2000) NOT NULL,
    "DataBaseValor" TIMESTAMP(7) NOT NULL,
    "Moeda" NVARCHAR2(2000) NOT NULL,
    "ValorOriginalContrato" BINARY_FLOAT NOT NULL,
    "ValorTotalProposicao" BINARY_FLOAT NOT NULL,
    "ReceitaDespesa" NUMBER(10) NOT NULL,
    "NumeroContrato" NVARCHAR2(2000) NOT NULL,
    "Termo" NVARCHAR2(2000) NOT NULL,
    "Fornecedor" NVARCHAR2(2000) NOT NULL,
    "ValorAtualContrato" BINARY_FLOAT NOT NULL,
    "NumeroReservaVerba" NVARCHAR2(2000) NOT NULL,
    "ValorReservaVerba" BINARY_FLOAT NOT NULL,
    "InicioVigenciaReserva" TIMESTAMP(7) NOT NULL,
    "FimVigenciaReserva" TIMESTAMP(7) NOT NULL,
    "NumeroProposicao" NVARCHAR2(2000) NOT NULL,
    "ProtoloExpediente" NVARCHAR2(2000) NOT NULL,
    "NumeroProcessoLicit" NVARCHAR2(2000) NOT NULL,
    "OutrasObservacoes" NVARCHAR2(2000),
    "ReuniaoId" NUMBER(10),
    "AnotacoesPrevia" NVARCHAR2(2000),
    "AjustesRd" NVARCHAR2(2000),
    "MotivoRetornoGrg" NVARCHAR2(2000),
    "MotivoRetornoDiretoriaResp" NVARCHAR2(2000),
    "Deliberacao" NVARCHAR2(2000),
    "IsExtraPauta" NUMBER(1) NOT NULL,
    "NumeroConselho" NVARCHAR2(2000),
    "SinteseProcessoFilePath" NVARCHAR2(2000) NOT NULL,
    "NotaTecnicaFilePath" NVARCHAR2(2000) NOT NULL,
    "PrdFilePath" NVARCHAR2(2000) NOT NULL,
    "ParecerJuridicoFilePath" NVARCHAR2(2000) NOT NULL,
    "TrFilePath" NVARCHAR2(2000) NOT NULL,
    "RelatorioTecnicoFilePath" NVARCHAR2(2000) NOT NULL,
    "PlanilhaQuantFilePath" NVARCHAR2(2000) NOT NULL,
    "EditalFilePath" NVARCHAR2(2000) NOT NULL,
    "ReservaVerbaFilePath" NVARCHAR2(2000) NOT NULL,
    "ScFilePath" NVARCHAR2(2000) NOT NULL,
    "RavFilePath" NVARCHAR2(2000) NOT NULL,
    "CronogramaFisFinFilePath" NVARCHAR2(2000) NOT NULL,
    "PcaFilePath" NVARCHAR2(2000) NOT NULL,
    "OutrosFilePath" NVARCHAR2(2000),
    "ResolucaoDiretoriaFilePath" NVARCHAR2(2000),
    "AreaAtual" NVARCHAR2(2000),
    "DescricaoFluxo" NVARCHAR2(2000),
    "TempoPrevPerm" NVARCHAR2(2000),
    "DescProxPasso" NVARCHAR2(2000),
    "TempoPermProx" NVARCHAR2(2000),
    "Seq" NUMBER(10),
    "ReuniaoId1" NUMBER(10),
    CONSTRAINT "PK_GRD_PROPOSICOES" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Proposicoes_Group" FOREIGN KEY ("AreaId") REFERENCES "GRD"."GRD_GROUPS" ("Id"),
    CONSTRAINT "FK_Proposicoes_User" FOREIGN KEY ("CriadorId") REFERENCES "GRD"."GRD_USERS" ("Id"),
    CONSTRAINT "FK_Reunioes_Prop" FOREIGN KEY ("ReuniaoId") REFERENCES "GRD"."GRD_REUNIOES" ("Id"),
    CONSTRAINT "FK_Reunioes_PropPrev" FOREIGN KEY ("ReuniaoId1") REFERENCES "GRD"."GRD_REUNIOES" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_USER_GROUP" (
    "GroupId" NUMBER(10) NOT NULL,
    "UserId" NUMBER(10) NOT NULL,
    CONSTRAINT "PK_GRD_USER_GROUP" PRIMARY KEY ("GroupId", "UserId"),
    CONSTRAINT "FK_UserGroup_GroupId" FOREIGN KEY ("GroupId") REFERENCES "GRD"."GRD_GROUPS" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_UserGroup_UserId" FOREIGN KEY ("UserId") REFERENCES "GRD"."GRD_USERS" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_ACAO_REUNIAO" (
    "AcaoId" NUMBER(10) NOT NULL,
    "ReuniaoId" NUMBER(10) NOT NULL,
    CONSTRAINT "PK_GRD_ACAO_REUNIAO" PRIMARY KEY ("AcaoId", "ReuniaoId"),
    CONSTRAINT "FK_AcaoReuniao_AcaoId" FOREIGN KEY ("AcaoId") REFERENCES "GRD"."GRD_ACOES" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_AcaoReuniao_ReuniaoId" FOREIGN KEY ("ReuniaoId") REFERENCES "GRD"."GRD_REUNIOES" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_ANDAMENTOS" (
    "Id" NUMBER(10) NOT NULL,
    "Data" TIMESTAMP(7) NOT NULL,
    "UserId" NUMBER(10) NOT NULL,
    "NomeResponsavel" NVARCHAR2(2000) NOT NULL,
    "Status" NUMBER(10) NOT NULL,
    "Descricao" NVARCHAR2(2000) NOT NULL,
    "AnexosFilePaths" NVARCHAR2(2000) NOT NULL,
    "AcaoId" NUMBER(10),
    CONSTRAINT "PK_GRD_ANDAMENTOS" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Acoes_Andamento" FOREIGN KEY ("AcaoId") REFERENCES "GRD"."GRD_ACOES" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Andamentos_Users" FOREIGN KEY ("UserId") REFERENCES "GRD"."GRD_USERS" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_LOGS_ACAO" (
    "Id" NUMBER(10) NOT NULL,
    "Tipo" NUMBER(10) NOT NULL,
    "AcaoRef" NVARCHAR2(2000) NOT NULL,
    "Diferenca" NVARCHAR2(2000) NOT NULL,
    "Data" TIMESTAMP(7) NOT NULL,
    "RespId" NUMBER(10) NOT NULL,
    "AcaoId" NUMBER(10),
    CONSTRAINT "PK_GRD_LOGS_ACAO" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LogsA_Acao" FOREIGN KEY ("AcaoId") REFERENCES "GRD"."GRD_ACOES" ("Id"),
    CONSTRAINT "FK_LogsA_User" FOREIGN KEY ("RespId") REFERENCES "GRD"."GRD_USERS" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_PART_REUNIAO" (
    "PartId" NUMBER(10) NOT NULL,
    "ReuniaoId" NUMBER(10) NOT NULL,
    CONSTRAINT "PK_GRD_PART_REUNIAO" PRIMARY KEY ("PartId", "ReuniaoId"),
    CONSTRAINT "FK_PartReuniao_PartId" FOREIGN KEY ("PartId") REFERENCES "GRD"."GRD_PARTICIPANTES" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_PartReuniao_ReuniaoId" FOREIGN KEY ("ReuniaoId") REFERENCES "GRD"."GRD_REUNIOES" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_PARTPREV_REUNIAO" (
    "PartId" NUMBER(10) NOT NULL,
    "ReuId" NUMBER(10) NOT NULL,
    CONSTRAINT "PK_GRD_PARTPREV_REUNIAO" PRIMARY KEY ("PartId", "ReuId"),
    CONSTRAINT "FK_PartPrevReuniao_PartId" FOREIGN KEY ("PartId") REFERENCES "GRD"."GRD_PARTICIPANTES" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_PartPrevReuniao_ReuId" FOREIGN KEY ("ReuId") REFERENCES "GRD"."GRD_REUNIOES" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_LOGS_PROPOSICAO" (
    "Id" NUMBER(10) NOT NULL,
    "Tipo" NUMBER(10) NOT NULL,
    "ProposicaoRef" NVARCHAR2(2000) NOT NULL,
    "Diferenca" NVARCHAR2(2000) NOT NULL,
    "Data" TIMESTAMP(7) NOT NULL,
    "RespId" NUMBER(10) NOT NULL,
    "PropId" NUMBER(10),
    CONSTRAINT "PK_GRD_LOGS_PROPOSICAO" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LogsP_Proposicao" FOREIGN KEY ("PropId") REFERENCES "GRD"."GRD_PROPOSICOES" ("Id"),
    CONSTRAINT "FK_LogsP_User" FOREIGN KEY ("RespId") REFERENCES "GRD"."GRD_USERS" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"GRD"."GRD_VOTOS" (
    "Id" NUMBER(10) NOT NULL,
    "ParticipanteId" NUMBER(10) NOT NULL,
    "VotoRd" NUMBER(10) NOT NULL,
    "ProposicaoId" NUMBER(10),
    CONSTRAINT "PK_GRD_VOTOS" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Proposicoes_Voto" FOREIGN KEY ("ProposicaoId") REFERENCES "GRD"."GRD_PROPOSICOES" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Votos_Part" FOREIGN KEY ("ParticipanteId") REFERENCES "GRD"."GRD_PARTICIPANTES" ("Id")
)';
END;
/

CREATE INDEX "GRD"."IX_GRD_ACAO_REUNIAO_ReuniaoId" ON "GRD"."GRD_ACAO_REUNIAO" ("ReuniaoId")
/

CREATE INDEX "GRD"."IX_GRD_ACOES_DiretoriaResId" ON "GRD"."GRD_ACOES" ("DiretoriaResId")
/

CREATE INDEX "GRD"."IX_GRD_ACOES_ResponsavelId" ON "GRD"."GRD_ACOES" ("ResponsavelId")
/

CREATE INDEX "GRD"."IX_GRD_ANDAMENTOS_AcaoId" ON "GRD"."GRD_ANDAMENTOS" ("AcaoId")
/

CREATE INDEX "GRD"."IX_GRD_ANDAMENTOS_UserId" ON "GRD"."GRD_ANDAMENTOS" ("UserId")
/

CREATE INDEX "GRD"."IX_GRD_LOGS_ACAO_AcaoId" ON "GRD"."GRD_LOGS_ACAO" ("AcaoId")
/

CREATE INDEX "GRD"."IX_GRD_LOGS_ACAO_RespId" ON "GRD"."GRD_LOGS_ACAO" ("RespId")
/

CREATE INDEX "GRD"."IX_GRD_LOGS_PROPOSICAO_PropId" ON "GRD"."GRD_LOGS_PROPOSICAO" ("PropId")
/

CREATE INDEX "GRD"."IX_GRD_LOGS_PROPOSICAO_RespId" ON "GRD"."GRD_LOGS_PROPOSICAO" ("RespId")
/

CREATE INDEX "GRD"."IX_GRD_LOGS_REUNIAO_RespId" ON "GRD"."GRD_LOGS_REUNIAO" ("RespId")
/

CREATE INDEX "GRD"."IX_GRD_LOGS_REUNIAO_ReuniaoId" ON "GRD"."GRD_LOGS_REUNIAO" ("ReuniaoId")
/

CREATE INDEX "GRD"."IX_GRD_PART_REUNIAO_ReuniaoId" ON "GRD"."GRD_PART_REUNIAO" ("ReuniaoId")
/

CREATE INDEX "GRD"."IX_GRD_PARTICIPANTES_AreaId" ON "GRD"."GRD_PARTICIPANTES" ("AreaId")
/

CREATE UNIQUE INDEX "GRD"."IX_GRD_PARTICIPANTES_UserId" ON "GRD"."GRD_PARTICIPANTES" ("UserId")
/

CREATE INDEX "GRD"."IX_GRD_PARTPREV_REUNIAO_ReuId" ON "GRD"."GRD_PARTPREV_REUNIAO" ("ReuId")
/

CREATE INDEX "GRD"."IX_GRD_PROPOSICOES_AreaId" ON "GRD"."GRD_PROPOSICOES" ("AreaId")
/

CREATE INDEX "GRD"."IX_GRD_PROPOSICOES_CriadorId" ON "GRD"."GRD_PROPOSICOES" ("CriadorId")
/

CREATE INDEX "GRD"."IX_GRD_PROPOSICOES_ReuniaoId" ON "GRD"."GRD_PROPOSICOES" ("ReuniaoId")
/

CREATE INDEX "GRD"."IX_GRD_PROPOSICOES_ReuniaoId1" ON "GRD"."GRD_PROPOSICOES" ("ReuniaoId1")
/

CREATE INDEX "GRD"."IX_GRD_USER_GROUP_UserId" ON "GRD"."GRD_USER_GROUP" ("UserId")
/

CREATE INDEX "GRD"."IX_GRD_VOTOS_ParticipanteId" ON "GRD"."GRD_VOTOS" ("ParticipanteId")
/

CREATE INDEX "GRD"."IX_GRD_VOTOS_ProposicaoId" ON "GRD"."GRD_VOTOS" ("ProposicaoId")
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20220805125201_FullModel', N'6.0.7')
/

